/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.csit228g4.huni;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Brent
 */
public class AddNewSongFrame extends javax.swing.JFrame implements DocumentListener {
    /**
     * Creates new form AddNewSong
     */
    public AddNewSongFrame() {
        initComponents();
        
        // Set frame behavior
        this.setTitle("New song");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        // Add event listeners to textfields
        txtSongTitle.getDocument().addDocumentListener(AddNewSongFrame.this);
        txtSongAuthor.getDocument().addDocumentListener(AddNewSongFrame.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSongTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSongAuthor = new javax.swing.JTextField();
        btnAddNewSong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Title");

        jLabel2.setText("Artist");

        btnAddNewSong.setText("Add Song");
        btnAddNewSong.setEnabled(false);
        btnAddNewSong.setFocusable(false);
        btnAddNewSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewSongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddNewSong)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtSongAuthor)
                        .addComponent(txtSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSongAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewSong)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewSongActionPerformed
        // Handles "Add Song" button click
        String title = txtSongTitle.getText();
        String author = txtSongAuthor.getText();

        // Pass information to DBHelper class
        int res = Session.dbh.addSong(title, author);
        
        // Hanle operation response
        switch (res) {
            // Success
            case 1 -> javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), "Song added");
            // Check failed
            case -1 -> javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), "Song already exists");
            // Other failure
            default -> javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), "Cannot add song");
        }
        // Close this frame
        this.dispose();
    }//GEN-LAST:event_btnAddNewSongActionPerformed
    
    @Override
    public void changedUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    @Override
    public void insertUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    @Override
    public void removeUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    private void updateButtonState() {
        // Handles button state when a change is made to textfields
        // Enables "Add Song" button if "Title" and "Artist" is not empty
        btnAddNewSong.setEnabled(txtSongTitle.getText().length() > 0 && txtSongAuthor.getText().length() > 0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewSongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewSongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewSongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewSongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewSongFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtSongAuthor;
    private javax.swing.JTextField txtSongTitle;
    // End of variables declaration//GEN-END:variables
}
