/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.csit228g4.huni;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Brent
 */
public class EditPlaylistFrame extends javax.swing.JFrame implements DocumentListener {
    private final Playlist pl;
    /**
     * Creates new form EditPlaylistFrame
     * @param pl
     */
    public EditPlaylistFrame(Playlist pl) {
        initComponents();
        this.pl = pl;
        
        // Set window behavior
        this.setTitle("Add a song to playlist");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        // Set textfield text
        txtPlaylistName.setText(pl.getName());
        
        // Add listeners
        txtPlaylistName.getDocument().addDocumentListener(EditPlaylistFrame.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlaylistName = new javax.swing.JTextField();
        btnRenamePlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Rename playlist");

        btnRenamePlaylist.setText("Rename");
        btnRenamePlaylist.setEnabled(false);
        btnRenamePlaylist.setFocusable(false);
        btnRenamePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenamePlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPlaylistName, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRenamePlaylist)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaylistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenamePlaylist))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRenamePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenamePlaylistActionPerformed
        // Handles "Rename" button click
        // Get playlist name
        String playlistName = txtPlaylistName.getText();
        
        // Set playlist to new name
        pl.setName(playlistName);
        
        // Pass data to DBHelper and call updatePlaylist method
        int res = Session.dbh.updatePlaylist(pl);
        
        // Handle user responses
        switch (res) {
            // Success
            case 1 -> javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), "Playlist renamed");
            // Fail
            default -> javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), "Cannot rename playlist");
        }
        
        if (res == 1)
            this.dispose();
    }//GEN-LAST:event_btnRenamePlaylistActionPerformed
    
    @Override
    public void changedUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    @Override
    public void insertUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    @Override
    public void removeUpdate(DocumentEvent e) {
        updateButtonState();
    }
    
    private void updateButtonState() {
        btnRenamePlaylist.setEnabled(txtPlaylistName.getText().length() > 0 && !txtPlaylistName.getText().equals(pl.getName()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditPlaylistFrame(new Playlist()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRenamePlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPlaylistName;
    // End of variables declaration//GEN-END:variables
}
